[ICXD] Upstream ICX-D LCC/HCC after PV
slimbootloader/slimbootloader pull request #1710
Opened 2022-10-06 00:50 UTC by cshur

Tested to boot Yocto and Windows.

Signed-off-by: cshur <cs.hur@intel.com>

2022-10-11 19:20 UTC, bejeanmo requested changes
Overall looks good, but many copyright headers need dates updated.

2022-10-11 19:29 UTC, cshur commented
Thanks for checking. Regarding dates, ICX team used BCD license from 1st time and if there is any changes from original file, we updated dates.

2022-10-11 19:31 UTC, sindhuragrandhi approved these changes

2022-10-11 19:31 UTC, bejeanmo approved these changes

2022-10-12 21:45 UTC, gdong1 reviewed
looks good to me.

2022-10-12 21:45 UTC, merged