Allow to load capsules signed with RSA3072 from raw partition
slimbootloader/slimbootloader pull request #1756
Opened 2022-11-16 13:36 UTC by arturkow2000

When loading capsule from raw partition, some check prevent capsules signed by a RSA3072 from being recognized as a valid capsule. Remove obsolete checks which expect RSA2048, signature type is already checked at a later stage from AuthenticateCapsule.

2022-11-16 15:33 UTC, bejeanmo approved these changes

2022-11-16 18:48 UTC, bejeanmo requested changes
Please add sign-off message to commit.

2022-11-16 20:52 UTC, lsubash approved these changes

2022-11-17 14:13 UTC, bejeanmo approved these changes

2022-11-18 03:32 UTC, gdong1 approved these changes

2022-11-18 03:32 UTC, merged