fix: [Common] Support FSP 2.3 FSP_NON_VOLATILE_STORAGE_HOB2
slimbootloader/slimbootloader pull request #1809
Opened 2023-01-16 04:03 UTC by koktong-ong

Implementation should search gFspNonVolatileStorageHob2Guid firstly and only search gFspNonVolatileStorageHobGuid when former one is not found.

Signed-off-by: Kobe <kok.tong.ong@intel.com>

2023-01-16 06:03 UTC, ywho79 approved these changes

2023-01-18 17:07 UTC, bejeanmo requested changes

2023-01-18 17:07 UTC, bejeanmo commented on BootloaderCorePkg/Library/FspSupportLib/FspSupportLib.c
> +  return GuidHobData;
FSP_NON_VOLATILE_STORAGE_HOB2 has a different format from FSP_NON_VOLATILE_STORAGE_HOB. The HOB now contains a pointer to the actual NVS data and length. Returning the HOB data here will have unexpected results.

2023-02-06 13:17 UTC, closed without merging

2023-02-06 13:18 UTC, koktong-ong commented
Thanks Bejean for the comment.
Will close this PR temporary.