Added FspNonVolatileStorageHob2 support in FspSupportLib
slimbootloader/slimbootloader pull request #1850
Opened 2023-03-21 06:39 UTC by koktong-ong

Support FSP 2.3 FSP_NON_VOLATILE_STORAGE_HOB2

2023-03-22 12:59 UTC, bejeanmo requested changes
Please address CI build failures. Otherwise PR looks good.

2023-03-22 15:11 UTC, koktong-ong commented
Done fixing the CI build errors

2023-03-22 17:44 UTC, gdong1 approved these changes

2023-03-24 07:04 UTC, ywho79 approved these changes

2023-03-24 12:32 UTC, bejeanmo approved these changes

2023-03-24 12:33 UTC, merged