[ADL] Update TPM event logging to match BIOS
slimbootloader/slimbootloader pull request #1859
Opened 2023-03-31 18:12 UTC by sean-m-mcginn

If measured boot disabled via BtG profile but enabled via SBL
config flag, skip logging startup locality TPM event

If measured boot enabled via BtG profile or SBL config flag, log
CRTM version TPM event

2023-04-04 19:20 UTC, lsubash commented on Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
> -      LdrFeatures &= ~FEATURE_MEASURED_BOOT;
Check when TPM init is not successful by BTG.

2023-04-13 16:43 UTC, gdong1 commented on BootloaderCommonPkg/Library/TpmLib/TpmLib.inf
> +  BootloaderCorePkg/BootloaderCorePkg.dec
BootloaderCommonPkg should not depend on BootloaderCorePkg (CorePkg could depend on CommonPkg).

2023-04-13 16:43 UTC, gdong1 commented on BootloaderCommonPkg/Include/Library/TpmLib.h
> +TpmLogCrtmVersionEvent(
It looks all the library API functions in this file, EFIAPI is missing. Please add it for both header file and implementation.

2023-04-13 18:14 UTC, lsubash commented on Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
> -  UINT32 Data;
why we are updating this structure?

2023-04-13 18:14 UTC, lsubash commented on Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
> +    CreateAuthorityPcrEvent (ActivePcrBanks);
Authority PCR also should have SCRTSTatus check.

2023-04-14 03:41 UTC, gdong1 commented on BootloaderCommonPkg/Library/TpmLib/TpmLib.inf
> +  BootloaderCoreLib
I think BootloaderCoreLib is not required to add.

2023-04-18 20:53 UTC, gdong1 approved these changes

2023-04-18 21:34 UTC, lsubash reviewed
Sean,would you split the changes in two patches?
Changes to eventlog lib are common to all platforms. 
For TGL/ADL/RPL, it looks fine. AcmPolicySts Struct aligns.
For EHL, CML platforms we need to check how this AcmPolicySts gets populated.

2023-04-20 20:05 UTC, lsubash approved these changes
looks good

2023-04-20 23:37 UTC, merged

2023-04-20 23:39 UTC, kvparikh89 requested changes

2023-04-20 23:39 UTC, kvparikh89 commented on BootloaderCommonPkg/Include/Library/TpmLib.h
Update  header year

2023-04-20 23:39 UTC, kvparikh89 commented on BootloaderCommonPkg/Library/TpmLib/TpmEventLog.c
Update header year

2023-04-20 23:39 UTC, kvparikh89 commented on BootloaderCommonPkg/Library/TpmLib/TpmLib.c
Update  header year

2023-04-20 23:39 UTC, kvparikh89 commented on BootloaderCommonPkg/Library/TpmLib/TpmLib.inf
Update  header year

2023-04-20 23:39 UTC, kvparikh89 commented on Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
> +  } else {
Set pointer to NULL

2023-04-20 23:39 UTC, kvparikh89 commented on Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
> +    DEBUG((DEBUG_INFO, "FEATURES_CFG_DATA is NULL"));
Refer other debug prints and edit for consistency

2023-04-20 23:39 UTC, kvparikh89 commented on Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
>    PLATFORM_DATA               *PlatformData;
Set pointer to NULL

2023-04-20 23:39 UTC, kvparikh89 commented on Platform/AlderlakeBoardPkg/Library/Stage1BBoardInitLib/Stage1BBoardInitLib.c
> +  if (PlatformData->BtGuardInfo.BootGuardCapability &&
Is NULL check required?

2023-04-20 23:39 UTC, kvparikh89 commented on Silicon/CommonSocPkg/Library/BootGuardLibCBnT/BootGuardTpmEventLogLib.c
Update header year