fix: [ADL] fix build errors for some board configs
slimbootloader/slimbootloader pull request #1962
Opened 2023-07-16 17:41 UTC by vincentchchen

Adjust FV image sizes for different combination of FSPDEBUG_MODE, ENABLE_SOURCE_DEBUG and ENABLE_FAST_BOOT

2023-07-18 17:03 UTC, sindhuragrandhi approved these changes

2023-07-18 17:51 UTC, bejeanmo requested changes
Please update copyright dates.

2023-07-18 20:38 UTC, bejeanmo approved these changes

2023-07-19 21:41 UTC, gdong1 approved these changes

2023-07-19 21:41 UTC, merged