Support bootloader a/b slot for Firmwareupdate Payload
slimbootloader/slimbootloader pull request #2146
Opened 2024-03-04 04:05 UTC by ceiba1985

Firmwareupadte Payload needs support bootloader a/b slots. The SBL update package is put to bootloader partition and will be updated during the OTA.

2024-03-12 13:25 UTC, bejeanmo requested changes

2024-03-12 13:25 UTC, bejeanmo commented on PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
> +  BootSlot = 0;
Align with previous variable initializations, and use spaces instead of tab characters.

2024-03-12 13:25 UTC, bejeanmo commented on PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
> +	DEBUG ((DEBUG_INFO, "Unable to find misc partition, Status = %r\n", Status));
Use spaces instead of tabs.

2024-03-18 17:52 UTC, gdong1 approved these changes
It looks good for me in general. Not sure the impact to change the default values for config data. I could merge it if there is no concern from others.

2024-03-20 16:30 UTC, marcjones-syspro commented
It is hard to understand why this patch is needed based on the description. Is there any documentation on A/B support? I couldn't find it. 

It seems that this patch is needed if A/B support is used and the firmware update image is written to the active "slot" and not to the specific SW partition number as indicated in CAPSULE_INFO_CFG_DATA. https://slimbootloader.github.io/security/firmware-update.html#capsule-location

2024-03-29 07:13 UTC, ceiba1985 commented
Suppose capsule is configured to be put in bootloader_a partition in CAPSULE_INFO_CFG_DATA.  And for a device, if it run in the A slot currently,  the old capsule is in bootloader_a partition.  But after OTA, the device will run in B slot, and the updated capsule is in bootloader_b partition. Without this patch, sbl will still read capsule from bootloader_a partition, whitch is an old one.

2024-04-02 18:31 UTC, gdong1 commented on PayloadPkg/FirmwareUpdate/GetCapsuleImage.c
> +
SBL capsule update image location is decided by the CapsuleInfo.
From the patch, it looks the expected SBL capsule image should be read from PART_A when mender OS is boot from PART_A, and read from PART_B when mender OS is boot from PART_B.
This is a new feature request, and the changes should not impact existing usage. (e.g. should not try to read boot slot info in normal capsule image loading).
I prefer adding a flag in CAPSULE_INFO_CFG_DATA to support this new feature. With this new flag, the change in this file looks like as below:
BootSlot = 0;
if (CapsuleInfo->CapsuleFlag & CAPSULE_FLAGS_MENDER !=0) {
  // update BootSlot as above
}

2024-05-10 03:06 UTC, gdong1 commented
close this PR as it is not needed.

2024-05-10 03:06 UTC, closed without merging